CREATE DATABASE grocery_store;
USE grocery_store;

-- 1. Supplier Table 
CREATE TABLE IF NOT EXISTS supplier (
	supp_id TINYINT PRIMARY KEY,
    supp_name VARCHAR(50),
    adress TEXT
);

-- 2. Categories Table 
CREATE TABLE IF NOT EXISTS categories (
	cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(50)
);

-- 3. Employees Table 
CREATE TABLE IF NOT EXISTS employees (
	emp_id TINYINT PRIMARY KEY,
    name VARCHAR(50),
    hire_date VARCHAR(50)
);

-- 4. Customers Table 
CREATE TABLE IF NOT EXISTS customers ( 
    cust_id SMALLINT PRIMARY KEY, 
    cust_name VARCHAR(255), 
    address TEXT 
);

-- 5. Products Table 
CREATE TABLE IF NOT EXISTS products (
	prod_id TINYINT PRIMARY KEY,
    name VARCHAR(50),
    supp_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10, 2),
    FOREIGN KEY (supp_id) REFERENCES supplier(supp_id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table 
CREATE TABLE IF NOT EXISTS orders ( 
    ord_id SMALLINT PRIMARY KEY, 
    cust_id SMALLINT, 
    emp_id TINYINT, 
    order_date VARCHAR(255), 
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
);

-- 7. Order_Details Table 
CREATE TABLE IF NOT EXISTS order_details ( 
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY, 
ord_id SMALLINT, 
prod_id TINYINT, 
quantity TINYINT, 
each_price DECIMAL(10,2), 
total_price DECIMAL(10,2), 
FOREIGN KEY (ord_id) REFERENCES orders(ord_id) 
ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (prod_id) REFERENCES products(prod_id) 
ON UPDATE CASCADE ON DELETE CASCADE 
);

SELECT * FROM categories;
SELECT * FROM customers;
SELECT * FROM employees;
SELECT * FROM products;
SELECT * FROM supplier;
SELECT * FROM orders;
SELECT * FROM order_details;

-- 1 . Customer Insights 
-- How many unique customers have placed orders? 
SELECT COUNT(DISTINCT cust_id) AS total_orders FROM orders;

-- Which customers have placed the highest number of orders? 
SELECT cust_id, COUNT(ord_id) AS total_orders FROM orders GROUP BY cust_id ORDER BY total_orders DESC;

-- What is the total and average purchase value per customer? 
SELECT cust_id, SUM(total_price) AS total_purchase, AVG(total_price) AS avg_purchase
FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY cust_id;

-- Who are the top 5 customers by total purchase amount?
SELECT cust_id, SUM(total_price) AS total_purchase
FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY cust_id
ORDER BY total_purchase DESC
LIMIT 5;

-- 2. Product Performance 
-- How many unique customers have placed orders? 
SELECT COUNT(DISTINCT cust_id) FROM orders;

-- What is the average price of products by category? 
SELECT cat_id, avg(price) AS avg_price
FROM products
GROUP BY cat_id;

-- Which products have the highest total sales volume (by quantity)?
SELECT prod_id, SUM(quantity) AS total_sales
FROM order_details
GROUP BY prod_id
ORDER BY total_sales DESC;

-- What is the total revenue generated by each product? 
SELECT prod_id, SUM(total_price) AS total_revenue
FROM order_details
GROUP BY prod_id;

-- How do product sales vary by category and supplier? 
SELECT p.supp_id, p.cat_id, SUM(od.total_price) AS sales
FROM products p JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.cat_id,p.supp_id
ORDER BY sales DESC;

-- 3. Sales and Order Trends 
-- How many orders have been placed in total?
SELECT COUNT(ord_id) AS total
FROM orders;

-- What is the average value per order? 
SELECT AVG(order_total) AS avg_value
FROM (SELECT ord_id, SUM(total_price) AS order_total
FROM order_details
GROUP BY ord_id) t;

-- On which dates were the most orders placed?
SELECT order_date,
       COUNT(*) AS total_orders
FROM orders
GROUP BY order_date
HAVING COUNT(*) = (
    SELECT MAX(order_count)
    FROM (
        SELECT COUNT(*) AS order_count
        FROM orders
        GROUP BY order_date
    ) t
);

-- What are the monthly trends in order volume and revenue? 
SELECT MONTH(str_to_date(o.order_date, '%m/%d/%Y')) AS month, SUM(od.quantity) AS valume, SUM(od.total_price) AS revenue
FROM orders as o JOIN order_details AS od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month DESC;

-- How do order patterns vary across weekdays and weekends? 
SELECT 
	CASE 
		WHEN dayofweek(str_to_date(order_date, '%m/%d/%Y')) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
	END AS day_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- 4 . Supplier Contribution 
-- How many suppliers are there in the database? 
SELECT COUNT(supp_id) AS total_suppliers
FROM supplier;

-- Which supplier provides the most products?
SELECT supp_id, COUNT(prod_id) AS total_products
FROM products
GROUP BY supp_id
ORDER BY total_products DESC
LIMIT 1;

-- What is the average price of products from each supplier?
SELECT supp_id, AVG(price) AS avg_price
FROM products
GROUP BY supp_id
ORDER BY avg_price DESC;

-- Which suppliers contribute the most to total product sales (by revenue)? 
SELECT p.supp_id, SUM(od.total_price) AS total_prod_sales
FROM products p JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.supp_id
ORDER BY total_prod_sales DESC;

-- 5 . Employee Performance 
-- How many employees have processed orders? 
SELECT COUNT(DISTINCT emp_id) AS total_emp
FROM orders;

-- Which employees have handled the most orders? 
SELECT emp_id, COUNT(ord_id) AS total_orders
FROM orders
GROUP BY emp_id
ORDER BY total_orders DESC;

-- What is the total sales value processed by each employee? 
SELECT o.emp_id, sum(total_price) AS total_sales
FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.emp_id;

-- What is the average order value handled per employee?
select emp_id, AVG(sum_ord_value) AS avg_ord_value
FROM(
SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS sum_ord_value
FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.emp_id, o.ord_id
) t
GROUP BY emp_id;

-- 6 . Order Details Deep Dive 
-- What is the relationship between quantity ordered and total price?
SELECT quantity, AVG(total_price) AS avg_price
FROM order_details
GROUP BY quantity
ORDER BY quantity DESC;

-- What is the average quantity ordered per product? 
SELECT AVG(quantity) avg_quantity, prod_id
FROM order_details
GROUP BY prod_id
ORDER BY avg_quantity DESC;

-- How does the unit price vary across products and orders? 
SELECT prod_id, ord_id, (total_price / quantity) AS unit_price
FROM order_details;